// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: words/v1/words.proto

package v1

import (
	pbentity "proxima/app/word/api/pbentity"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Word          string                 `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	Definition    string                 `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_words_v1_words_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_words_v1_words_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_words_v1_words_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReq) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateReq) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *CreateReq) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

type CreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRes) Reset() {
	*x = CreateRes{}
	mi := &file_words_v1_words_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRes) ProtoMessage() {}

func (x *CreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_words_v1_words_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRes.ProtoReflect.Descriptor instead.
func (*CreateRes) Descriptor() ([]byte, []int) {
	return file_words_v1_words_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_words_v1_words_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_words_v1_words_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_words_v1_words_proto_rawDescGZIP(), []int{2}
}

func (x *GetReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          *pbentity.Words        `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRes) Reset() {
	*x = GetRes{}
	mi := &file_words_v1_words_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRes) ProtoMessage() {}

func (x *GetRes) ProtoReflect() protoreflect.Message {
	mi := &file_words_v1_words_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRes.ProtoReflect.Descriptor instead.
func (*GetRes) Descriptor() ([]byte, []int) {
	return file_words_v1_words_proto_rawDescGZIP(), []int{3}
}

func (x *GetRes) GetWord() *pbentity.Words {
	if x != nil {
		return x.Word
	}
	return nil
}

var File_words_v1_words_proto protoreflect.FileDescriptor

const file_words_v1_words_proto_rawDesc = "" +
	"\n" +
	"\x14words/v1/words.proto\x12\bwords.v1\x1a\x14pbentity/words.proto\"Q\n" +
	"\tCreateReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x12\n" +
	"\x04word\x18\x02 \x01(\tR\x04word\x12\x1e\n" +
	"\n" +
	"definition\x18\x03 \x01(\tR\n" +
	"definition\"\x1b\n" +
	"\tCreateRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x18\n" +
	"\x06GetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"-\n" +
	"\x06GetRes\x12#\n" +
	"\x04word\x18\x01 \x01(\v2\x0f.pbentity.WordsR\x04word2f\n" +
	"\x05Words\x122\n" +
	"\x06Create\x12\x13.words.v1.CreateReq\x1a\x13.words.v1.CreateRes\x12)\n" +
	"\x03Get\x12\x10.words.v1.GetReq\x1a\x10.words.v1.GetResB\x1fZ\x1dproxima/app/word/api/words/v1b\x06proto3"

var (
	file_words_v1_words_proto_rawDescOnce sync.Once
	file_words_v1_words_proto_rawDescData []byte
)

func file_words_v1_words_proto_rawDescGZIP() []byte {
	file_words_v1_words_proto_rawDescOnce.Do(func() {
		file_words_v1_words_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_words_v1_words_proto_rawDesc), len(file_words_v1_words_proto_rawDesc)))
	})
	return file_words_v1_words_proto_rawDescData
}

var file_words_v1_words_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_words_v1_words_proto_goTypes = []any{
	(*CreateReq)(nil),      // 0: words.v1.CreateReq
	(*CreateRes)(nil),      // 1: words.v1.CreateRes
	(*GetReq)(nil),         // 2: words.v1.GetReq
	(*GetRes)(nil),         // 3: words.v1.GetRes
	(*pbentity.Words)(nil), // 4: pbentity.Words
}
var file_words_v1_words_proto_depIdxs = []int32{
	4, // 0: words.v1.GetRes.word:type_name -> pbentity.Words
	0, // 1: words.v1.Words.Create:input_type -> words.v1.CreateReq
	2, // 2: words.v1.Words.Get:input_type -> words.v1.GetReq
	1, // 3: words.v1.Words.Create:output_type -> words.v1.CreateRes
	3, // 4: words.v1.Words.Get:output_type -> words.v1.GetRes
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_words_v1_words_proto_init() }
func file_words_v1_words_proto_init() {
	if File_words_v1_words_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_words_v1_words_proto_rawDesc), len(file_words_v1_words_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_words_v1_words_proto_goTypes,
		DependencyIndexes: file_words_v1_words_proto_depIdxs,
		MessageInfos:      file_words_v1_words_proto_msgTypes,
	}.Build()
	File_words_v1_words_proto = out.File
	file_words_v1_words_proto_goTypes = nil
	file_words_v1_words_proto_depIdxs = nil
}
