// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package orderinfo

import (
	"context"

	"go-zero-rpc-demo/orderrpc/order_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetOrderInfoReq  = order_pb.GetOrderInfoReq
	GetOrderInfoResp = order_pb.GetOrderInfoResp

	OrderInfo interface {
		// 定义一个 OrderInfo 一元 rpc 方法，请求体和响应体必填。
		GetOrderInfo(ctx context.Context, in *GetOrderInfoReq, opts ...grpc.CallOption) (*GetOrderInfoResp, error)
	}

	defaultOrderInfo struct {
		cli zrpc.Client
	}
)

func NewOrderInfo(cli zrpc.Client) OrderInfo {
	return &defaultOrderInfo{
		cli: cli,
	}
}

// 定义一个 OrderInfo 一元 rpc 方法，请求体和响应体必填。
func (m *defaultOrderInfo) GetOrderInfo(ctx context.Context, in *GetOrderInfoReq, opts ...grpc.CallOption) (*GetOrderInfoResp, error) {
	client := order_pb.NewOrderInfoClient(m.cli.Conn())
	return client.GetOrderInfo(ctx, in, opts...)
}
