// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package hello

import "github.com/gogf/gf/v2/net/ghttp"

type Hello struct {
}

func NewHello() *Hello {
	return &Hello{}
}

func (h *Hello) SayHello(req *ghttp.Request) {
	req.Response.Writeln("你好你好呀")
}
