// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pbentity/words.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Words struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                                //
	Uid                uint32                 `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`                              //
	Word               string                 `protobuf:"bytes,3,opt,name=Word,proto3" json:"Word,omitempty"`                             //
	Definition         string                 `protobuf:"bytes,4,opt,name=Definition,proto3" json:"Definition,omitempty"`                 //
	ExampleSentence    string                 `protobuf:"bytes,5,opt,name=ExampleSentence,proto3" json:"ExampleSentence,omitempty"`       //
	ChineseTranslation string                 `protobuf:"bytes,6,opt,name=ChineseTranslation,proto3" json:"ChineseTranslation,omitempty"` //
	Pronunciation      string                 `protobuf:"bytes,7,opt,name=Pronunciation,proto3" json:"Pronunciation,omitempty"`           //
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`                   //
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`                   //
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Words) Reset() {
	*x = Words{}
	mi := &file_pbentity_words_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Words) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Words) ProtoMessage() {}

func (x *Words) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_words_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Words.ProtoReflect.Descriptor instead.
func (*Words) Descriptor() ([]byte, []int) {
	return file_pbentity_words_proto_rawDescGZIP(), []int{0}
}

func (x *Words) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Words) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Words) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *Words) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *Words) GetExampleSentence() string {
	if x != nil {
		return x.ExampleSentence
	}
	return ""
}

func (x *Words) GetChineseTranslation() string {
	if x != nil {
		return x.ChineseTranslation
	}
	return ""
}

func (x *Words) GetPronunciation() string {
	if x != nil {
		return x.Pronunciation
	}
	return ""
}

func (x *Words) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Words) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_pbentity_words_proto protoreflect.FileDescriptor

const file_pbentity_words_proto_rawDesc = "" +
	"\n" +
	"\x14pbentity/words.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x02\n" +
	"\x05Words\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12\x10\n" +
	"\x03Uid\x18\x02 \x01(\rR\x03Uid\x12\x12\n" +
	"\x04Word\x18\x03 \x01(\tR\x04Word\x12\x1e\n" +
	"\n" +
	"Definition\x18\x04 \x01(\tR\n" +
	"Definition\x12(\n" +
	"\x0fExampleSentence\x18\x05 \x01(\tR\x0fExampleSentence\x12.\n" +
	"\x12ChineseTranslation\x18\x06 \x01(\tR\x12ChineseTranslation\x12$\n" +
	"\rPronunciation\x18\a \x01(\tR\rPronunciation\x128\n" +
	"\tCreatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAtB\x1fZ\x1dproxima/app/word/api/pbentityb\x06proto3"

var (
	file_pbentity_words_proto_rawDescOnce sync.Once
	file_pbentity_words_proto_rawDescData []byte
)

func file_pbentity_words_proto_rawDescGZIP() []byte {
	file_pbentity_words_proto_rawDescOnce.Do(func() {
		file_pbentity_words_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_words_proto_rawDesc), len(file_pbentity_words_proto_rawDesc)))
	})
	return file_pbentity_words_proto_rawDescData
}

var file_pbentity_words_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_words_proto_goTypes = []any{
	(*Words)(nil),                 // 0: pbentity.Words
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_words_proto_depIdxs = []int32{
	1, // 0: pbentity.Words.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.Words.UpdatedAt:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pbentity_words_proto_init() }
func file_pbentity_words_proto_init() {
	if File_pbentity_words_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_words_proto_rawDesc), len(file_pbentity_words_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_words_proto_goTypes,
		DependencyIndexes: file_pbentity_words_proto_depIdxs,
		MessageInfos:      file_pbentity_words_proto_msgTypes,
	}.Build()
	File_pbentity_words_proto = out.File
	file_pbentity_words_proto_goTypes = nil
	file_pbentity_words_proto_depIdxs = nil
}
