// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package word

import (
	"gf_star/api/word"
	userLogic "gf_star/internal/logic/user"
	wordLogic "gf_star/internal/logic/word"
)

type ControllerV1 struct {
	user userLogic.Users
	word wordLogic.Word
}

func NewV1() word.IWordV1 {
	return &ControllerV1{
		user: *userLogic.New(),
		word: *wordLogic.New(),
	}
}
