// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userinfo

import (
	"context"

	"go-zero-demo/userrpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserInfoReq  = pb.GetUserInfoReq
	GetUserInfoResp = pb.GetUserInfoResp

	UserInfo interface {
		// 定义一个 UserInfo 一元 rpc 方法，请求体和响应体必填。
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
	}

	defaultUserInfo struct {
		cli zrpc.Client
	}
)

func NewUserInfo(cli zrpc.Client) UserInfo {
	return &defaultUserInfo{
		cli: cli,
	}
}

// 定义一个 UserInfo 一元 rpc 方法，请求体和响应体必填。
func (m *defaultUserInfo) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := pb.NewUserInfoClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}
