
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:941002@tcp(127.0.0.1:3306)/goframe"
        descriptionTag: true
        tables: "book, user, dept, emp, hobby"
        jsonCase: "Snake"


  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app