// Code generated by goctl. DO NOT EDIT.
package types

type UserCreateReq struct {
	Name string `json:"name"`
}

type UserCreateResp struct {
	Flag bool `json:"flag"`
}

type UserInfoReq struct {
	UserId int64 `form:"user_id"` // get 方法参数
}

type UserInfoResp struct {
	UserId int64  `json:"user_id"`
	Name   string `json:"name"`
}

type UserRegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type UserRegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserUpdateReq struct {
	UserId int64  `json:"user_id"`
	Name   string `json:"name"`
}

type UserUpdateResp struct {
	Flag bool `json:"flag"`
}
