// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// bookDao is the data access object for the table book.
// You can define custom methods on it to extend its functionality as needed.
type bookDao struct {
	*internal.BookDao
}

var (
	// Book is a globally accessible object for table book operations.
	Book = bookDao{internal.NewBookDao()}
)

// Add your custom methods and functionality below.
