// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// deptDao is the data access object for the table dept.
// You can define custom methods on it to extend its functionality as needed.
type deptDao struct {
	*internal.DeptDao
}

var (
	// Dept is a globally accessible object for table dept operations.
	Dept = deptDao{internal.NewDeptDao()}
)

// Add your custom methods and functionality below.
