// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// empDao is the data access object for the table emp.
// You can define custom methods on it to extend its functionality as needed.
type empDao struct {
	*internal.EmpDao
}

var (
	// Emp is a globally accessible object for table emp operations.
	Emp = empDao{internal.NewEmpDao()}
)

// Add your custom methods and functionality below.
