// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf_demo/internal/dao/internal"
)

// hobbyDao is the data access object for the table hobby.
// You can define custom methods on it to extend its functionality as needed.
type hobbyDao struct {
	*internal.HobbyDao
}

var (
	// Hobby is a globally accessible object for table hobby operations.
	Hobby = hobbyDao{internal.NewHobbyDao()}
)

// Add your custom methods and functionality below.
